### ISSUE TITLE
[Bug?] MenuEntry position

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#129] opened 2016-03-19 14:12 UTC
From wiki:
> Separators: If the positions of two consecutive entries are not in the same thousand group, Drombler FX will add a separator between them.

I have three groups that need to me separated from each other. The first group contains items whose position is between 10000 and 11000, meaning that those will b grouped together. The second group contains positions between 20000-21000 and the third from 30000-31000. The wiki states that those would each be separated into a group but drombler puts them together in one single group without using separators. IS this a bug or did I misunderstand the wiki? Are you just checking for the last 4 digits of the number to determine a group? Because that would explain it. By just using the last 4 digits, each group would internally be seen as 0000-1000, meaning they belong in the same group.

###### EDIT: 
Looks like it was some graphical glitch. It sometimes happens but after minimizing the window it is gone. Sorry for the inconvenience.

**Comment by puce77** [comment] 2016-03-19 19:04
Currently, I'm closing this as a JavaFX bug, not a Drombler FX bug.
Try to reproduce the issue with pure JavaFX code and file an issue at: http://bugs.java.com/

If you cannot reproduce the issue, try to debug it and verify, that the Separators really were added: https://github.com/Drombler/drombler-fx/blob/develop/drombler-fx-core-action/src/main/java/org/drombler/fx/core/action/AbstractMenuItemContainer.java

You might also want to try and use Scenic View to verify if it really is a JavaFX issue: http://fxexperience.com/scenic-view/

**Comment by puce77** [comment] 2016-03-19 19:05
If you think it's a Drombler FX issue, feel free to re-open this issue.

**Closed by puce77** 2016-03-19 19:04 UTC
