### ISSUE TITLE
Spilt pane divider bug

### ISSUE THREAD

**Issue by SirWindfield** [Drombler/drombler-fx#115] opened 2016-03-10 13:11 UTC
If you move the split pane divider that is used between the left and the center elements in a test application generated by ```mvn archetype:generate -DarchetypeGroupId=org.drombler.fx -DarchetypeArtifactId=drombler-fx-maven-archetype-application -DarchetypeVersion=0.7 -DgroupId=com.mycompany.test -DartifactId=test -Dversion=0.1-SNAPSHOT -DbrandingId=foo```, both dividers, the one that splits the top and the center view and the one that is in between the bottom and the center view, move to the edge of the application on OS X. [Here](https://youtu.be/_2nl1BuRoAg) is a youtube video show casing the bug.

**Comment by puce77** [comment] 2016-03-10 23:51
Duplicate of #46
(see comments)

**Closed by puce77** 2016-03-10 23:51 UTC
Labels: duplicate

**Comment by SirWindfield** [comment] 2016-03-11 00:50
Haha sorry, missed that!
